DEPTS.PGM: depts.pgm.sqlrpgle DEPARTMENT.TABLE DEPTS.FILE
EMPLOYEES.PGM: employees.pgm.sqlrpgle EMPLOYEE.TABLE EMPS.FILE
CSCRGFS50.PGM: CSCRGFS50.pgm.rpgle

TESTSFL.PGM: testsfl.pgm.rpgle TEST.FILE MYDSPF.FILE